[2024-05-15T01:29:22.841+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:29:22.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:29:22.861+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:29:22.860+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:29:23.086+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:29:26.362+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:29:26.361+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:29:26.777+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:29:26.776+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:29:27.023+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 4.254 seconds
[2024-05-15T01:29:57.645+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:29:57.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:29:57.673+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:29:57.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:29:57.752+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:29:57.970+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:29:57.968+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:29:58.193+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:29:58.192+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:29:58.349+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.752 seconds
[2024-05-15T01:30:29.074+0000] {processor.py:161} INFO - Started process (PID=73) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:30:29.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:30:29.092+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:30:29.091+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:30:29.150+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:30:29.322+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:30:29.321+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:30:29.514+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:30:29.513+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:30:29.757+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.732 seconds
[2024-05-15T01:31:00.389+0000] {processor.py:161} INFO - Started process (PID=80) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:31:00.393+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:31:00.397+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:31:00.396+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:31:00.422+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:31:00.532+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:31:00.531+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:31:00.695+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:31:00.694+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:31:00.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.407 seconds
[2024-05-15T01:31:31.305+0000] {processor.py:161} INFO - Started process (PID=87) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:31:31.309+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:31:31.320+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:31:31.317+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:31:31.366+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:31:31.522+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:31:31.521+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:31:31.686+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:31:31.679+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:31:31.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.541 seconds
[2024-05-15T01:32:02.492+0000] {processor.py:161} INFO - Started process (PID=94) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:32:02.507+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:32:02.516+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:32:02.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:32:02.616+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:32:02.848+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:32:02.847+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:32:03.042+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:32:03.040+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:32:03.184+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.786 seconds
[2024-05-15T01:32:33.626+0000] {processor.py:161} INFO - Started process (PID=100) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:32:33.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:32:33.633+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:32:33.631+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:32:33.659+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:32:33.731+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:32:33.731+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:32:33.846+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:32:33.845+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:32:33.956+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.342 seconds
[2024-05-15T01:33:04.318+0000] {processor.py:161} INFO - Started process (PID=107) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:33:04.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:33:04.324+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:33:04.323+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:33:04.359+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:33:04.461+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:33:04.460+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:33:04.528+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:33:04.528+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:33:04.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.293 seconds
[2024-05-15T01:33:34.680+0000] {processor.py:161} INFO - Started process (PID=114) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:33:34.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:33:34.686+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:33:34.685+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:33:34.717+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:33:34.794+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:33:34.793+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:33:34.860+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:33:34.859+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:33:34.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.243 seconds
[2024-05-15T01:34:05.186+0000] {processor.py:161} INFO - Started process (PID=121) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:34:05.189+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:34:05.195+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:34:05.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:34:05.222+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:34:05.277+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:34:05.276+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:34:05.330+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:34:05.329+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:34:05.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.203 seconds
[2024-05-15T01:34:35.436+0000] {processor.py:161} INFO - Started process (PID=129) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:34:35.438+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:34:35.443+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:34:35.441+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:34:35.480+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:34:35.553+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:34:35.552+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:34:35.626+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:34:35.625+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:34:35.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.271 seconds
[2024-05-15T01:35:05.861+0000] {processor.py:161} INFO - Started process (PID=136) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:35:05.864+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:35:05.868+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:35:05.867+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:35:05.887+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:35:05.925+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:35:05.925+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:35:05.967+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:35:05.967+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:35:05.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.148 seconds
[2024-05-15T01:35:36.145+0000] {processor.py:161} INFO - Started process (PID=143) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:35:36.147+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:35:36.150+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:35:36.149+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:35:36.178+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:35:36.224+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:35:36.224+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:35:36.288+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:35:36.287+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:35:36.340+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.205 seconds
[2024-05-15T01:36:06.441+0000] {processor.py:161} INFO - Started process (PID=151) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:36:06.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:36:06.447+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:36:06.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:36:06.465+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:36:06.510+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:36:06.509+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:36:06.586+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:36:06.585+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:36:06.652+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.220 seconds
[2024-05-15T01:36:37.001+0000] {processor.py:161} INFO - Started process (PID=158) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:36:37.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:36:37.010+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:36:37.007+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:36:37.096+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:36:37.304+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:36:37.303+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:36:37.465+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:36:37.464+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:36:37.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.704 seconds
[2024-05-15T01:37:08.155+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:37:08.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:37:08.198+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:37:08.185+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:37:08.374+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:37:08.638+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:37:08.636+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:37:08.874+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:37:08.873+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:37:08.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.904 seconds
[2024-05-15T01:37:39.358+0000] {processor.py:161} INFO - Started process (PID=171) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:37:39.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:37:39.362+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:37:39.362+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:37:39.392+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:37:39.472+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:37:39.471+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:37:39.549+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:37:39.549+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:37:39.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.278 seconds
[2024-05-15T01:38:09.936+0000] {processor.py:161} INFO - Started process (PID=178) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:09.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:38:09.944+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:09.943+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:09.982+0000] {processor.py:840} INFO - DAG(s) 'user_processing' retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:10.081+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:10.080+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-05-15T01:38:10.149+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:10.149+0000] {dag.py:3954} INFO - Setting next_dagrun for user_processing to 2024-05-14 00:00:00+00:00, run_after=2024-05-15 00:00:00+00:00
[2024-05-15T01:38:10.200+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.285 seconds
[2024-05-15T01:38:25.121+0000] {processor.py:161} INFO - Started process (PID=185) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:25.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:38:25.134+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:25.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:25.154+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:25.149+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:38:25.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:25.240+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.151 seconds
[2024-05-15T01:38:55.485+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:55.488+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:38:55.491+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:55.490+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:55.498+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:38:55.495+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:38:55.500+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:38:55.537+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.063 seconds
[2024-05-15T01:39:25.721+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:39:25.723+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:39:25.727+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:39:25.726+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:39:25.733+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:39:25.731+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:39:25.734+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:39:25.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.065 seconds
[2024-05-15T01:39:56.021+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:39:56.025+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:39:56.030+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:39:56.028+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:39:56.039+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:39:56.037+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:39:56.041+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:39:56.117+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.113 seconds
[2024-05-15T01:40:03.140+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:40:03.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:40:03.146+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:40:03.144+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:40:03.169+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:40:03.159+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:40:03.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:40:03.280+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.172 seconds
[2024-05-15T01:40:31.481+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:40:31.486+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:40:31.491+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:40:31.490+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:40:31.507+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:40:31.505+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:40:31.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:40:31.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.099 seconds
[2024-05-15T01:41:01.732+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:41:01.734+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:41:01.736+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:41:01.735+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:41:01.744+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:41:01.741+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:41:01.747+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:41:01.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.080 seconds
[2024-05-15T01:41:31.995+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:41:31.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:41:31.998+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:41:31.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:41:32.004+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:41:32.002+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:41:32.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:41:32.034+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.049 seconds
[2024-05-15T01:42:02.210+0000] {processor.py:161} INFO - Started process (PID=236) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:42:02.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:42:02.214+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:42:02.214+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:42:02.217+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:42:02.216+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:42:02.218+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:42:02.247+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.045 seconds
[2024-05-15T01:42:32.493+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:42:32.494+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:42:32.496+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:42:32.496+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:42:32.507+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:42:32.503+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:42:32.509+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:42:32.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.088 seconds
[2024-05-15T01:43:03.025+0000] {processor.py:161} INFO - Started process (PID=250) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:43:03.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:43:03.052+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:43:03.050+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:43:03.105+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:43:03.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:43:03.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:43:03.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.324 seconds
[2024-05-15T01:43:33.579+0000] {processor.py:161} INFO - Started process (PID=257) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:43:33.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:43:33.587+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:43:33.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:43:33.601+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:43:33.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:43:33.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:43:33.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.106 seconds
[2024-05-15T01:44:03.767+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:44:03.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:44:03.771+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:44:03.770+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:44:03.775+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:44:03.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:44:03.776+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:44:03.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.054 seconds
[2024-05-15T01:44:34.017+0000] {processor.py:161} INFO - Started process (PID=271) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:44:34.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:44:34.020+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:44:34.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:44:34.024+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:44:34.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:44:34.025+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:44:34.057+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.047 seconds
[2024-05-15T01:45:04.267+0000] {processor.py:161} INFO - Started process (PID=278) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:45:04.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:45:04.271+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:45:04.270+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:45:04.278+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:45:04.275+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:45:04.279+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:45:04.326+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.071 seconds
[2024-05-15T01:45:34.527+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:45:34.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:45:34.532+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:45:34.531+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:45:34.538+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:45:34.536+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:45:34.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:45:34.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.074 seconds
[2024-05-15T01:46:04.826+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:46:04.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:46:04.829+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:46:04.829+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:46:04.835+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:46:04.833+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:46:04.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:46:04.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.061 seconds
[2024-05-15T01:46:35.095+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:46:35.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:46:35.100+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:46:35.099+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:46:35.107+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:46:35.105+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:46:35.108+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:46:35.153+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.070 seconds
[2024-05-15T01:47:05.339+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:47:05.342+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:47:05.343+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:47:05.343+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:47:05.348+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:47:05.347+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:47:05.349+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:47:05.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.052 seconds
[2024-05-15T01:47:35.550+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:47:35.552+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:47:35.553+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:47:35.552+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:47:35.557+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:47:35.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:47:35.558+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:47:35.589+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.048 seconds
[2024-05-15T01:48:05.784+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:48:05.788+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:48:05.791+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:48:05.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:48:05.799+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:48:05.796+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:48:05.800+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:48:05.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.093 seconds
[2024-05-15T01:48:36.039+0000] {processor.py:161} INFO - Started process (PID=327) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:48:36.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:48:36.057+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:48:36.055+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:48:36.118+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:48:36.089+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:48:36.121+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:48:36.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.192 seconds
[2024-05-15T01:49:06.371+0000] {processor.py:161} INFO - Started process (PID=334) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:49:06.374+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:49:06.376+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:49:06.375+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:49:06.383+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:49:06.380+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:49:06.384+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:49:06.416+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.058 seconds
[2024-05-15T01:49:36.624+0000] {processor.py:161} INFO - Started process (PID=341) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:49:36.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:49:36.627+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:49:36.626+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:49:36.633+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:49:36.631+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:49:36.634+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:49:36.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.051 seconds
[2024-05-15T01:50:06.865+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:50:06.869+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:50:06.871+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:50:06.870+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:50:06.876+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:50:06.873+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:50:06.878+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:50:06.907+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.055 seconds
[2024-05-15T01:50:37.230+0000] {processor.py:161} INFO - Started process (PID=355) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:50:37.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:50:37.238+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:50:37.236+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:50:37.252+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:50:37.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:50:37.254+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:50:37.335+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.118 seconds
[2024-05-15T01:51:07.417+0000] {processor.py:161} INFO - Started process (PID=362) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:51:07.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:51:07.423+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:51:07.422+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:51:07.434+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:51:07.430+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:51:07.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:51:07.473+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.066 seconds
[2024-05-15T01:51:37.650+0000] {processor.py:161} INFO - Started process (PID=370) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:51:37.653+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:51:37.655+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:51:37.654+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:51:37.659+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:51:37.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:51:37.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:51:37.694+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.052 seconds
[2024-05-15T01:52:07.912+0000] {processor.py:161} INFO - Started process (PID=377) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:52:07.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:52:07.915+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:52:07.915+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:52:07.921+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:52:07.920+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:52:07.922+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:52:07.960+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.057 seconds
[2024-05-15T01:52:38.199+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:52:38.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:52:38.205+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:52:38.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:52:38.213+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:52:38.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:52:38.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:52:38.267+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.082 seconds
[2024-05-15T01:53:08.471+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:53:08.474+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:53:08.476+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:53:08.475+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:53:08.486+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:53:08.483+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:53:08.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:53:08.539+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.084 seconds
[2024-05-15T01:53:38.787+0000] {processor.py:161} INFO - Started process (PID=398) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:53:38.789+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:53:38.791+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:53:38.790+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:53:38.796+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:53:38.794+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:53:38.797+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:53:38.838+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.068 seconds
[2024-05-15T01:54:09.095+0000] {processor.py:161} INFO - Started process (PID=406) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:54:09.098+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:54:09.101+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:54:09.100+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:54:09.114+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:54:09.109+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:54:09.116+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:54:09.192+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.126 seconds
[2024-05-15T01:54:39.471+0000] {processor.py:161} INFO - Started process (PID=413) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:54:39.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:54:39.478+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:54:39.477+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:54:39.486+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:54:39.484+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:54:39.488+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:54:39.545+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.099 seconds
[2024-05-15T01:55:09.752+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:55:09.754+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:55:09.757+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:55:09.756+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:55:09.767+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:55:09.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:55:09.769+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:55:09.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.082 seconds
[2024-05-15T01:55:40.061+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:55:40.063+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:55:40.065+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:55:40.064+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:55:40.072+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:55:40.069+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:55:40.073+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:55:40.107+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.055 seconds
[2024-05-15T01:56:10.331+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:56:10.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:56:10.336+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:56:10.335+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:56:10.342+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:56:10.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:56:10.343+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:56:10.381+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.062 seconds
[2024-05-15T01:56:40.607+0000] {processor.py:161} INFO - Started process (PID=440) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:56:40.609+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:56:40.612+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:56:40.611+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:56:40.621+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:56:40.619+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:56:40.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:56:40.675+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.082 seconds
[2024-05-15T01:57:10.896+0000] {processor.py:161} INFO - Started process (PID=447) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:57:10.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:57:10.901+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:57:10.900+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:57:10.912+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:57:10.908+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:57:10.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:57:10.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.090 seconds
[2024-05-15T01:57:41.200+0000] {processor.py:161} INFO - Started process (PID=454) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:57:41.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:57:41.206+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:57:41.205+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:57:41.214+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:57:41.211+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:57:41.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:57:41.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.071 seconds
[2024-05-15T01:58:11.484+0000] {processor.py:161} INFO - Started process (PID=461) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:58:11.487+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:58:11.489+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:58:11.489+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:58:11.498+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:58:11.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:58:11.501+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:58:11.576+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.106 seconds
[2024-05-15T01:58:41.772+0000] {processor.py:161} INFO - Started process (PID=469) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:58:41.775+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:58:41.777+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:58:41.776+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:58:41.781+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:58:41.780+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:58:41.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:58:41.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.056 seconds
[2024-05-15T01:59:12.085+0000] {processor.py:161} INFO - Started process (PID=476) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:59:12.087+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:59:12.089+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:59:12.088+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:59:12.094+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:59:12.092+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:59:12.096+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:59:12.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.060 seconds
[2024-05-15T01:59:42.449+0000] {processor.py:161} INFO - Started process (PID=483) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:59:42.454+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T01:59:42.464+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:59:42.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:59:42.487+0000] {logging_mixin.py:188} INFO - [2024-05-15T01:59:42.471+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T01:59:42.490+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T01:59:42.651+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.240 seconds
[2024-05-15T02:00:12.737+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:00:12.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:00:12.742+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:00:12.741+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:00:12.750+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:00:12.747+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:00:12.752+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:00:12.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.079 seconds
[2024-05-15T02:00:42.951+0000] {processor.py:161} INFO - Started process (PID=497) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:00:42.952+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:00:42.953+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:00:42.953+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:00:42.957+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:00:42.956+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:00:42.958+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:00:42.987+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.045 seconds
[2024-05-15T02:01:13.174+0000] {processor.py:161} INFO - Started process (PID=504) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:01:13.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:01:13.184+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:01:13.179+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:01:13.191+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:01:13.189+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:01:13.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:01:13.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.127 seconds
[2024-05-15T02:01:37.356+0000] {processor.py:161} INFO - Started process (PID=511) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:01:37.367+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:01:37.369+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:01:37.368+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:01:37.386+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:01:37.379+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:01:37.389+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:01:37.477+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.129 seconds
[2024-05-15T02:02:07.740+0000] {processor.py:161} INFO - Started process (PID=518) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:02:07.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:02:07.749+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:02:07.747+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:02:07.761+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:02:07.756+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:02:07.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:02:07.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.128 seconds
[2024-05-15T02:02:37.939+0000] {processor.py:161} INFO - Started process (PID=525) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:02:37.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:02:37.944+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:02:37.943+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:02:37.952+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:02:37.949+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:02:37.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:02:37.995+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.069 seconds
[2024-05-15T02:03:08.167+0000] {processor.py:161} INFO - Started process (PID=532) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:03:08.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:03:08.172+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:03:08.171+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:03:08.179+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:03:08.176+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:03:08.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:03:08.216+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.061 seconds
[2024-05-15T02:03:38.474+0000] {processor.py:161} INFO - Started process (PID=540) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:03:38.475+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:03:38.477+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:03:38.476+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:03:38.483+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:03:38.481+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:03:38.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:03:38.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.061 seconds
[2024-05-15T02:04:08.770+0000] {processor.py:161} INFO - Started process (PID=547) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:04:08.774+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:04:08.775+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:04:08.775+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:04:08.782+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:04:08.780+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:04:08.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:04:08.820+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.062 seconds
[2024-05-15T02:04:39.453+0000] {processor.py:161} INFO - Started process (PID=554) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:04:39.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:04:39.462+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:04:39.460+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:04:39.479+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:04:39.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:04:39.481+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:04:39.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.148 seconds
[2024-05-15T02:05:09.757+0000] {processor.py:161} INFO - Started process (PID=561) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:05:09.758+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:05:09.760+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:05:09.759+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:05:09.765+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:05:09.763+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:05:09.766+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:05:09.805+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.057 seconds
[2024-05-15T02:05:39.985+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:05:39.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:05:39.997+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:05:39.994+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:05:40.015+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:05:40.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:05:40.017+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:05:40.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.076 seconds
[2024-05-15T02:06:10.210+0000] {processor.py:161} INFO - Started process (PID=575) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:06:10.212+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:06:10.214+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:06:10.213+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:06:10.218+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:06:10.217+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:06:10.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:06:10.249+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.046 seconds
[2024-05-15T02:06:40.466+0000] {processor.py:161} INFO - Started process (PID=582) to work on /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:06:40.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/api_kafka_dag.py for tasks to queue
[2024-05-15T02:06:40.473+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:06:40.471+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:06:40.484+0000] {logging_mixin.py:188} INFO - [2024-05-15T02:06:40.480+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/api_kafka_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/api_kafka_dag.py", line 74, in <module>
    stream_data()
  File "/opt/airflow/dags/api_kafka_dag.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-05-15T02:06:40.486+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/api_kafka_dag.py
[2024-05-15T02:06:40.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/api_kafka_dag.py took 0.073 seconds
